# Gitlab CI

# acquire git source path. 
before_script:
  - whoami
  - export CURRENT_PATH=$(pwd)
  - export CURRENT_TIME=$(date +%Y%m%d_%H%M)
  - cp /home/gitlab-runner/testving-compose.yml /home/gitlab-runner/testving-$CURRENT_TIME.yml
  - sed -i s^@CI_RUNNER_PATH@^$CURRENT_PATH^g /home/gitlab-runner/testving-$CURRENT_TIME.yml

stages:
  - build
  - test

job-build:
  stage: build
  script:
    - docker-compose -f /home/gitlab-runner/testving-$CURRENT_TIME.yml up -d
    - docker exec -it testving bash -c "cd /home/gitlab-runner/ving; npm install"

job-test:
  stage: test
  script: 
    - echo 'job-test'
    - ls
    - ps -ef | grep redis
    - pwd

after_script:
  - echo 'global after script'