# Gitlab CI

before_script:
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
  - chmod 700 ~/.ssh/id_rsa
  # TEST
  - ssh-keyscan -H $XMDBHOST >> ~/.ssh/known_hosts
  - cat ~/.ssh/id_rsa
  - cat ~/.ssh/known_hosts

stages:
  - build
  - test
  - deploy

job-build:
  stage: build
  script:
    - npm install
    - ls
    - cd server;ls
    - cd lib;ls
    - cd ../../ui-server;ls
job-test:
  stage: test
  script: 
    - echo 'job-test'
    - ls
    - pwd

job-deploy:
  stage: deploy
  script: echo 'job-deploy'

after_script:
  - echo 'global after script'
  - whoami
  - pwd
  - echo $ACCOUNT
  - echo $XMDBHOST
  - cat ~/.ssh/id_rsa
  - cat ~/.ssh/known_hosts
  - ssh -i ~/.ssh/id_rsa $ACCOUNT@$XMDBHOST ls