# Gitlab CI

# acquire git source path. 
before_script:
  - whoami
  - export CURRENT_PATH=$(pwd)
  - export CURRENT_TIME=$(date +%Y%m%d_%H%M)
  # - cp /home/gitlab-runner/testving-compose.yml /home/gitlab-runner/testving-$CURRENT_TIME.yml
  # - sed -i s^@CI_RUNNER_PATH@^$CURRENT_PATH^g /home/gitlab-runner/testving-$CURRENT_TIME.yml

stages:
  - build
  - test

job-build:
  stage: build
  cache:
    policy: push
    paths:
    - node_modules/
  script:
    - export CURRENT_PATH=$(pwd)
    - echo $CURRENT_PATH
    - cd $CURRENT_PATH
    - npm install
    - echo $APP_LAUNCHER
    - echo $VING_SERVICE
    - sudo bash -c "export APP_LAUNCHER=$APP_LAUNCHER;export VING_SERVICE=$VING_SERVICE;./testenv.sh"
    - cd $CURRENT_PATH/server;ls
    - cd $CURRENT_PATH/server/lib;ls
    - cd $CURRENT_PATH/ui-server;ls
    # - docker-compose -f /home/gitlab-runner/testving-$CURRENT_TIME.yml up -d
    # - docker exec -it testving bash -c "cd /home/gitlab-runner/ving; npm install"

job-test:
  stage: test
  cache:
    policy: pull
    paths:
      - node_modules/
  script: 
    - echo 'job-test'
    - ls
    - ps -ef | grep node
    - pwd

after_script:
  - echo 'global after script'