# Gitlab CI

before_script:
  - echo 'global before script'
  - whoami
  - pwd

stages:
  - build
  - test
  - deploy

job-build:
  stage: build
  script:
    - npm install
    - ls
    - cd server;ls
    - cd lib;ls
    - cd ../../ui-server;ls
job-test:
  stage: test
  script: 
    - echo 'job-test'
    - ls
    - pwd

job-deploy:
  stage: deploy
  script: echo 'job-deploy'

after_script:
  - echo 'global after script'
  - whoami
  - pwd